[package]
name = "plasma_state"
version = "0.1.0"
edition = "2021"

[features]
borsh = ["dep:borsh"]

[dependencies]
bs58 = { workspace = true }
bytemuck = { workspace = true }
borsh = { version = "0.10.0", optional = true }
fixed = "1.27.0"

[dev-dependencies]
rand = "0.7.0"
